package constants

type AVAILABILITY string

const (
	AVAILABLE    AVAILABILITY = "AVAILABILITY"
	OUT_OF_STOCK AVAILABILITY = "OUT_OF_STOCK"
	DISCONTINUED AVAILABILITY = "DISCONTINUED"
	UPCOMING     AVAILABILITY = "UPCOMING"
)
